App\Entity\Book:
    # collectionOperations:
    #     get:
    #         normalization_context:
    #             groups: ['read']
  attributes:
    normalization_context: {'groups': ['read']}
    denormalization_context: {'groups': ['write']}